import Head from 'next/head';
import styled from 'styled-components';
import { Wrapper } from '../components/Wrapper';
import { Sidebar } from '../components/Sidebar';

export default function Home() {
	return (
		<Wrapper>
			<Head>
				<title>WhatsApp 2.0</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Sidebar />
			<Main>
				<h1>WhatsApp 2.0</h1>
			</Main>
		</Wrapper>
	);
}

const Main = styled.div`
	flex: 1;
	display: flex;
	align-items: center;
	justify-content: center;
	background: ${({ theme }) => theme.colors.grey1};

	h1 {
		color: ${({ theme }) => theme.colors.grey3};
	}
`;
